#redis服务配置
jedis :  
  pool :  
    host : 127.0.0.1  
    port : 6379  
    config :  
      maxTotal: 100  
      maxIdle: 10  
      maxWaitMillis : 100000

#服务启动端口
server :  
  port :  8080

#数据库配置
jdbc:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/world
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    typeAliasesPackage: com.xiaour.spring.boot.mapper
    typeHandlersPackage: org.apache.ibatis.type.LocalDateTypeHandler
    mapperLocations: classpath:com/xiaour/spring/boot/mapper/*.xml
    configLocation: classpath:mybatis-config.xml
    
# 日志输出
logging: 
    file: D:/boot.log
#    level: 
#        com.ibatis:DEBUG
#        root:DEBUG

task:
    cron:0 0/5 * * * ?
       
    
